### PR TITLE
[common] services not detected by agent

### PR DESCRIPTION
**Pull request by pabloopez**
Signed-off-by: pablopez <pablo.lopezzaldivar@sysdig.com>

### CODE REVIEW

**Comment by pmusa** [comment]
For reference: https://sysdigcloud.slack.com/archives/GPW3T4T7V/p1640094519010100

**Comment by pmusa** [comment]
As discussed in slack, the entire `k8s_extra_resources` should be removed.

**Comment by pabloopez** [comment]
agreed!

**Comment by pmusa** [comment]
That is quite some change. Unfortunately, I dont have to knowledge to comment on it.

**Pull request merged**
