### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by theluke**
remove the assets.zip file and add its contents in a bespoke folder

### CODE REVIEW

**Comment by theluke** [comment]
@pabloopez : please approve this PR, I made a mistake and already added the rest of the `assets.zip` files to `main`, I did not check and somehow the `main` branch was selected when I uploaded the files. Apologies

**Comment by pabloopez** [comment]
no problem @theluke! So, a subset of the changes in this PR where applied in the commit you pushed to main 10 minutes ago, right?

**Comment by theluke** [comment]
Yes it was, by mistake, unfortunately....
I also need to push more changes, but I will do another PR since I do not want to work on this one anymore.
Can I squash and merge?

**Review by pabloopez — APPROVED** [review]
LGTM

**Pull request merged**
