### PR TITLE
check user for track test

### PR DESCRIPTION
**Pull request by pabloopez**
init.sh not working as expected for instruqt track test

### CODE REVIEW

**Comment by pmusa** [comment]
I suggest reverting this and using the following trick to test a track (**notice the checkout command**):

```
cd /tmp
git clone https://github.com/draios/instruqt-assets.git
git checkout my-test-branch
cp -r /tmp/instruqt-assets/common/* /root/
cd ~
```

**Comment by theluke** [comment]
Thank you @pmusa, how do I use the commands that you listed? Directly in
the CLI ?

**Comment by pmusa** [comment]
The commands above are already used in all the `track_scripts/setup-server` scripts, for tracks that use the prepare-track scripts. The only difference I am pointing out is that you can use `git checkout track-test-debug`, where `track-test-debug` is a branch with changes that you want to test.

**Comment by theluke** [comment]
Thank you Pablo, yes I understand, where should I use `git[...]` typing it manually at the prompt or altering the original script?

**Comment by pabloopez** [comment]
Changes reverted.

#theluke Original script in the track, where the init.sh script is loaded.

**Pull request merged**
