### PR TITLE
[dev-account-provisioner] integrate with lab setup

### PR DESCRIPTION
**Pull request by pabloopez**
Ticket -> https://sysdig.atlassian.net/browse/ET-32

# Problem statement:

Hands-on labs on Instruqt require to our students to have access to a Sysdig account to take the training. Most of them have access to one, but some don’t, or don’t want to use a trial or can’t use the production account of their company to complete training and learn more about the product.

# Suggested approach

An alternative approach is to have a training account in which temporary users are created. These users will meet the next requirements:
- Least Privilege Access enforced. No access to admin functions on the account, just the basics to complete any training available in our catalogue.
- Users are deleted when the track is done
- User creation/deletion is automated and integrated with the rest of instruct tooling

### CODE REVIEW

**Comment by pabloopez** [comment]
this is ready for review. It has been tested and meets the initial criteria:
- user created when track is started
- user credentials are used to deploy sysdig components on the lab infra
- user deleted when track is stoped
- install logs are visible to the user, and does not hands the track-setup script

The current state reuses the logic for tests, but we should merge both approaches into one (setup for track being tested, setup for track for which a sysdig saas account is provisioned).

**Comment by pabloopez** [comment]
It can be tested live here: https://play.instruqt.com/sysdig/tracks/tmp-dev-account-provisioner

And track source files are here: https://github.com/draios/instruqt/pull/517

**Review by mikescholl-sysdig — CHANGES_REQUESTED** [review]
LGTM

**Review by mikescholl-sysdig — APPROVED** [review]

**Comment by pabloopez** [comment]
Merging, this is working fine with the new lab.

**Comment by pabloopez** [comment]
Let's not delete the branch, as some of the new tracks are still poining to `dev-account-provisioner`

**Pull request merged**
