### PR TITLE
Add parameter to capture metadata in k3s

### PR DESCRIPTION
**Pull request by theluke**
Add parameter to capture metadata in k3s containerd clusters
Closes draios/instruqt#200

### CODE REVIEW

**Comment by theluke** [comment]
closes draios/instruqt#200

**Comment by pabloopez** [comment]
LGTM, thx @theluke!

**Review by pabloopez — APPROVED** [review]
well done!

**Comment by pmusa** [comment]
This is a great PR @theluke . Some courses have their own `values.yaml` file (e.g. `prometheus-extends-sysdig-maths`). In those cases, we will need to remember to add those parameters. I think that adding this setting as a parameter might be a more scalable solution.

It seems we can do something like `--set sysdig.settings.cri.socket_path=/run/k3s/containerd/containerd.sock`. (I did not test it yet, though.)

**Comment by theluke** [comment]
Thank you very much @pmusa :smile: , two questions to better understand your approach:

1. when a course has its own `values.yaml`, are you saying that we have to manually add the code below to the `values.yaml` specific to the course? 

```yaml
--set sysdig.settings.cri.socket_path=/run/k3s/containerd/containerd.sock
```

2. For all other courses, if your code works as expected, where should we add it? Not in `values.yaml`, somewhere else, right?

3. It is too early to merge this PR yet, right?

Thank you again for your patience here.

**Comment by pmusa** [comment]
> 3. It is too early to merge this PR yet, right?

I would hold this PR a bit longer if it does not stop you from working, as we discuss the best solution.

> 2. when a course has its own values.yaml, are you saying that we have to manually add the code below to the values.yaml specific to the course?
> --set sysdig.settings.cri.socket_path=/run/k3s/containerd/containerd.sock

Not this code, but your original one. Here is an example:
https://github.com/draios/instruqt-assets/tree/prometheus-extends-sysdig-maths-1/monitor/prometheus-extends-sysdig-maths/sysdig-agent

The course above has its custom `values.yaml` file, which means we need to add the following settings to the file.
```
cri:
  socket_path: ...
```


> For all other courses, if your code works as expected, where should we add it? Not in values.yaml, somewhere else, right?

If we add the suggested code to the `install_with_helm.sh` [script](https://github.com/draios/instruqt-assets/blob/8aaf89b4c21095d703b5d0dc1b64e75864d9cfd3/common/prepare-track/install_with_helm.sh#L48), it will add the setting regardless of the `values.yaml` file. If it works, we don't need to remember to add the setting to every custom yaml file.

Let me know if the explanation is clear.

**Comment by theluke** [comment]
Thank you @pmusa 

1) I can wait on this no prob, I think @pabloopez however needs this sooner?
2) got it!
3) explanation is spot on, thanks a lot.

Last thing: since the parameter in question is specific to `K3S/containerd`, is it worth it to (I do not know how) ensure that it is applied only in such environments and not everywhere? In case in the future we move out of K3S ?? Maybe I am paranoid.

**Comment by pmusa** [comment]
That is the advantage of setting it in the Helm script versus the YAML file. If we move from K3s, we will have to update too many things along with that. I would not worry about it.

**Comment by theluke** [comment]
Do you guys want me to remove this commit, keep the same PR and add another commit for the `helm` file?

**Comment by pabloopez** [comment]
+1 to the Helm approach, as explained in the other issue (instruqt repo) and privately with you both.

**Comment by pabloopez** [comment]
Not sure if this is clear, but observe that the parameter:

```
--set sysdig.settings.cri.socket_path=
```

follows the same structure as the file:

```
sysdig:
  settings:
    cri:
      socket_path: ...
```

**Comment by pabloopez** [comment]
this applies to the rest of the options too.

**Review by pabloopez — APPROVED** [review]
LGTM

**Comment by pabloopez** [comment]
let's also all consider that we'll need to apply this *patch* to the init.sh extra configs when we are using it in a podman packer image

**Comment by theluke** [comment]
> let's also all consider that we'll need to apply this patch to the init.sh extra configs when we are using it in a podman packer image

@pabloopez sorry mate...you lost me here, what do you want me to do?

**Comment by theluke** [comment]
lo and behold, the command works, the metadata are captured !

**Pull request merged**
