### PR TITLE
[falco-rule-exceptions] track creation review

### PR DESCRIPTION
**Pull request by pmusa**

### CODE REVIEW

**Review by pabloopez — APPROVED** [review]
LGTM

**Comment by pabloopez** [comment]
Related to this [PR](https://github.com/draios/instruqt/pull/103#pullrequestreview-807708352) on `draios/instruqt`.

**Comment by pabloopez** [comment]
The only thing I do not like about this approach is that it is clear which rule needs to be modified in challenge 3. But when the append feature is merged this changes.

**Comment by pmusa** [comment]
I totally agree that things are too explicit. We could remove the "challenge X" comment and sort the rules to make it not so obvious.

**Comment by pabloopez** [comment]
> I totally agree that things are too explicit. We could remove the "challenge X" comment and sort the rules to make it not so obvious.

done, I am merging this

**Pull request merged**
